blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Alejandrehl/frontend-joyofenergy-Angular#readme
    about: Please read the documentation before creating an issue.
  - name: 💬 Discussions
    url: https://github.com/Alejandrehl/frontend-joyofenergy-Angular/discussions
    about: Ask questions and share ideas in our discussions. 